### ISSUE TITLE
identifiability

### ISSUE THREAD

**Issue by theorashid** [statneutrino/bayes_football_scores#1]
Maggie Lieu's model has identifiability issues (I think). By giving `att` and `def` their own mean, only one of them can be identifiable. It's better to have some overall intercept, and then centre `att` and `def` around 0. See [here](https://github.com/theorashid/probabilistic-programming-packages/blob/main/models/R/stan.stan).

**Comment by statneutrino** [comment]
@theorashid This is great thanks for sharing - will try the new STAN model.

I have been inspired by your probabilistic repo and I'm going to try and create a Flask app that displays predictions with interactive probabilities.

**Comment by theorashid** [comment]
That would be really cool. We could try and make a model that's better than these, perhaps in time for next season. We could use championship data and have a multilevel model for leagues. We could include form, like this [model](https://gianluca.statistica.it/post/2021-06-14-euros-prediction/), or even include form with a hidden markov model like [this political forecast](https://alexandorra.github.io/pollsposition_blog/popularity/macron/hidden%20markov%20models/polls/2021/05/16/hmm-popularity.html).

Loads of really cool options here. Keen to help with whatever.
